apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: streamlit-hello-s2i-build
spec:
  source:
    type: Git
    git:
      uri: https://github.com/Starias22/streamlit-hello-s2i  # Your repository URL
  strategy:
    type: Docker
    dockerStrategy:
      dockerfile: |
        FROM python:3.8-slim
        WORKDIR /app
        # COPY requirements.txt /app/requirements.txt
        # RUN pip install --no-cache-dir -r /app/requirements.txt
        RUN pip install streamlit
        COPY . /app
        EXPOSE 8501
        CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
  output:
    to:
      kind: ImageStreamTag
      name: streamlit-hello-docker:latest
  triggers: []  # Disable automatic triggers
